version: '3.4'

# This is an example docker-compose file to quickly test an IPFS Cluster
# with multiple peers on a contained environment.

# It runs 3 cluster peers (cluster5-0, cluster5-1...) attached to kubo daemons
# (ipfs5-0, ipfs5-1...) using the CRDT consensus component. Cluster peers
# autodiscover themselves using mDNS on the docker internal network.
#
# To interact with the cluster use "ipfs-cluster-ctl" (the cluster5-0 API port is
# exposed to the locahost. You can also "docker exec -ti cluster5-0 sh" and run
# it from the container. "ipfs-cluster-ctl peers ls" should show all 3 peers a few
# seconds after start.
#
# For persistence, a "compose" folder is created and used to store configurations
# and states. This can be used to edit configurations in subsequent runs. It looks
# as follows:
#
# compose/
# |-- cluster5-0
# |-- cluster5-1
# |-- ...
# |-- ipfs5-0
# |-- ipfs5-1
# |-- ...
#
# During the first start, default configurations are created for all peers.

services:

##################################################################################
## Cluster PEER 0 ################################################################
##################################################################################

  ipfs5-0:
    container_name: ipfs5-0
    image: ipfs/kubo:release
    ports:
      - "4001:4001" # ipfs swarm - expose if needed/wanted
      - "5001:5001" # ipfs api - expose if needed/wanted
      - "8080:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./compose/ipfs5-0:/data/ipfs

  cluster5-0:
    container_name: cluster5-0
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs5-0
    environment:
      CLUSTER_PEERNAME: cluster5-0
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs5-0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
          # Open API port (allows ipfs-cluster-ctl usage on host)
          - "127.0.0.1:9094:9094"
          # The cluster swarm port would need  to be exposed if this container
          # was to connect to cluster peers on other hosts.
          # But this is just a testing cluster.
          # - "9095:9095" # Cluster IPFS Proxy endpoint
          # - "9096:9096" # Cluster swarm endpoint
    volumes:
      - ./compose/cluster5-0:/data/ipfs-cluster

##################################################################################
## Cluster PEER 1 ################################################################
##################################################################################

# See Cluster PEER 0 for comments (all removed here and below)
  ipfs5-1:
    container_name: ipfs5-1
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs5-1:/data/ipfs

  cluster5-1:
    container_name: cluster5-1
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs5-1
    environment:
      CLUSTER_PEERNAME: cluster5-1
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs5-1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster5-1:/data/ipfs-cluster

##################################################################################
## Cluster PEER 2 ################################################################
##################################################################################

# See Cluster PEER 0 for comments (all removed here and below)
  ipfs5-2:
    container_name: ipfs5-2
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs5-2:/data/ipfs

  cluster5-2:
    container_name: cluster5-2
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs5-2
    environment:
      CLUSTER_PEERNAME: cluster5-2
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs5-2/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster5-2:/data/ipfs-cluster

##################################################################################
## Cluster PEER 3 ################################################################
##################################################################################
  ipfs5-3:
    container_name: ipfs5-3
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs5-3:/data/ipfs

  cluster5-3:
    container_name: cluster5-3
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs5-3
    environment:
      CLUSTER_PEERNAME: cluster5-3
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs5-3/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster5-3:/data/ipfs-cluster


##################################################################################
## Cluster PEER 4 ################################################################
##################################################################################
  ipfs5-4:
    container_name: ipfs5-4
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs5-4:/data/ipfs

  cluster5-4:
    container_name: cluster5-4
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs5-4
    environment:
      CLUSTER_PEERNAME: cluster5-4
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs5-4/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster5-4:/data/ipfs-cluster


# For adding more peers, copy PEER 1 and rename things to ipfs5-2, cluster5-2.
# Keep bootstrapping to cluster5-0.