version: '3.4'

# This is an example docker-compose file to quickly test an IPFS Cluster
# with multiple peers on a contained environment.

# It runs 3 cluster peers (cluster20-10-0, cluster20-1...) attached to kubo daemons
# (ipfs20-0, ipfs1...) using the CRDT consensus component. Cluster peers
# autodiscover themselves using mDNS on the docker internal network.
#
# To interact with the cluster use "ipfs-cluster-ctl" (the cluster20-10-0 API port is
# exposed to the locahost. You can also "docker exec -ti cluster20-10-0 sh" and run
# it from the container. "ipfs-cluster-ctl peers ls" should show all 3 peers a few
# seconds after start.
#
# For persistence, a "compose" folder is created and used to store configurations
# and states. This can be used to edit configurations in subsequent runs. It looks
# as follows:
#
# compose/
# |-- cluster20-10-0
# |-- cluster20-1
# |-- ...
# |-- ipfs20-0
# |-- ipfs1
# |-- ...
#
# During the first start, default configurations are created for all peers.

services:

##################################################################################
## Cluster PEER 0 ################################################################
##################################################################################

  ipfs20-0:
    container_name: ipfs20-0
    image: ipfs/kubo:release
    ports:
      - "4001:4001" # ipfs swarm - expose if needed/wanted
      - "5001:5001" # ipfs api - expose if needed/wanted
      - "8080:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./compose/ipfs20-0:/data/ipfs

  cluster20-0:
    container_name: cluster20-0
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-0
    environment:
      CLUSTER_PEERNAME: cluster20-0
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
          # Open API port (allows ipfs-cluster-ctl usage on host)
          - "127.0.0.1:9094:9094"
          # The cluster swarm port would need  to be exposed if this container
          # was to connect to cluster peers on other hosts.
          # But this is just a testing cluster.
          # - "9095:9095" # Cluster IPFS Proxy endpoint
          # - "9096:9096" # Cluster swarm endpoint
    volumes:
      - ./compose/cluster20-0:/data/ipfs-cluster

##################################################################################
## Cluster PEER 1 ################################################################
##################################################################################

# See Cluster PEER 0 for comments (all removed here and below)
  ipfs20-1:
    container_name: ipfs20-1
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-1:/data/ipfs

  cluster20-1:
    container_name: cluster20-1
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-1
    environment:
      CLUSTER_PEERNAME: cluster20-1
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-1:/data/ipfs-cluster

##################################################################################
## Cluster PEER 2 ################################################################
##################################################################################

# See Cluster PEER 0 for comments (all removed here and below)
  ipfs20-2:
    container_name: ipfs20-2
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-2:/data/ipfs

  cluster20-2:
    container_name: cluster20-2
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-2
    environment:
      CLUSTER_PEERNAME: cluster20-2
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-2/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-2:/data/ipfs-cluster

##################################################################################
## Cluster PEER 3 ################################################################
##################################################################################
  ipfs20-3:
    container_name: ipfs20-3
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-3:/data/ipfs

  cluster20-3:
    container_name: cluster20-3
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-3
    environment:
      CLUSTER_PEERNAME: cluster20-3
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-3/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-3:/data/ipfs-cluster


##################################################################################
## Cluster PEER 4 ################################################################
##################################################################################
  ipfs20-4:
    container_name: ipfs20-4
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-4:/data/ipfs

  cluster20-4:
    container_name: cluster20-4
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-4
    environment:
      CLUSTER_PEERNAME: cluster20-4
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-4/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-4:/data/ipfs-cluster

##################################################################################
## Cluster PEER 5 ################################################################
##################################################################################

# See Cluster PEER 0 for comments (all removed here and below)
  ipfs20-5:
    container_name: ipfs20-5
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-5:/data/ipfs

  cluster20-5:
    container_name: cluster20-5
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-5
    environment:
      CLUSTER_PEERNAME: cluster20-5
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-5/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-5:/data/ipfs-cluster

##################################################################################
## Cluster PEER 6 ################################################################
##################################################################################

# See Cluster PEER 0 for comments (all removed here and below)
  ipfs20-6:
    container_name: ipfs20-6
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-6:/data/ipfs

  cluster20-6:
    container_name: cluster20-6
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-6
    environment:
      CLUSTER_PEERNAME: cluster20-6
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-6/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-6:/data/ipfs-cluster

##################################################################################
## Cluster PEER 7 ################################################################
##################################################################################
  ipfs20-7:
    container_name: ipfs20-7
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-7:/data/ipfs

  cluster20-7:
    container_name: cluster20-7
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-7
    environment:
      CLUSTER_PEERNAME: cluster20-7
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-7/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-7:/data/ipfs-cluster


##################################################################################
## Cluster PEER 8 ################################################################
##################################################################################
  ipfs20-8:
    container_name: ipfs20-8
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-8:/data/ipfs

  cluster20-8:
    container_name: cluster20-8
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-8
    environment:
      CLUSTER_PEERNAME: cluster20-8
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-8/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-8:/data/ipfs-cluster

##################################################################################
## Cluster PEER 9 ################################################################
##################################################################################
  ipfs20-9:
    container_name: ipfs20-9
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-9:/data/ipfs

  cluster20-9:
    container_name: cluster20-9
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-9
    environment:
      CLUSTER_PEERNAME: cluster20-9
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-9/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-9:/data/ipfs-cluster


##################################################################################
## Cluster PEER 10 ################################################################
##################################################################################

# See Cluster PEER 0 for comments (all removed here and below)
  ipfs20-10:
    container_name: ipfs20-10
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-10:/data/ipfs

  cluster20-10:
    container_name: cluster20-10
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-10
    environment:
      CLUSTER_PEERNAME: cluster20-10
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-10/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-10:/data/ipfs-cluster

##################################################################################
## Cluster PEER 11 ################################################################
##################################################################################

# See Cluster PEER 0 for comments (all removed here and below)
  ipfs20-11:
    container_name: ipfs20-11
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-11:/data/ipfs

  cluster20-11:
    container_name: cluster20-11
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-11
    environment:
      CLUSTER_PEERNAME: cluster20-11
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-11/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-11:/data/ipfs-cluster

##################################################################################
## Cluster PEER 12 ################################################################
##################################################################################
  ipfs20-12:
    container_name: ipfs20-12
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-12:/data/ipfs

  cluster20-12:
    container_name: cluster20-12
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-12
    environment:
      CLUSTER_PEERNAME: cluster20-12
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-12/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-12:/data/ipfs-cluster


##################################################################################
## Cluster PEER 13 ################################################################
##################################################################################
  ipfs20-13:
    container_name: ipfs20-13
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-13:/data/ipfs

  cluster20-13:
    container_name: cluster20-13
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-13
    environment:
      CLUSTER_PEERNAME: cluster20-13
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-13/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-13:/data/ipfs-cluster

##################################################################################
## Cluster PEER 14 ################################################################
##################################################################################
  ipfs20-14:
    container_name: ipfs20-14
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-14:/data/ipfs

  cluster20-14:
    container_name: cluster20-14
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-14
    environment:
      CLUSTER_PEERNAME: cluster20-14
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-14/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-14:/data/ipfs-cluster

##################################################################################
## Cluster PEER 15 ################################################################
##################################################################################
  ipfs20-15:
    container_name: ipfs20-15
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-15:/data/ipfs

  cluster20-15:
    container_name: cluster20-15
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-15
    environment:
      CLUSTER_PEERNAME: cluster20-15
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-15/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-15:/data/ipfs-cluster


##################################################################################
## Cluster PEER 16 ################################################################
##################################################################################

# See Cluster PEER 0 for comments (all removed here and below)
  ipfs20-16:
    container_name: ipfs20-16
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-16:/data/ipfs

  cluster20-16:
    container_name: cluster20-16
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-16
    environment:
      CLUSTER_PEERNAME: cluster20-16
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-16/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-16:/data/ipfs-cluster

##################################################################################
## Cluster PEER 17 ################################################################
##################################################################################

# See Cluster PEER 0 for comments (all removed here and below)
  ipfs20-17:
    container_name: ipfs20-17
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-17:/data/ipfs

  cluster20-17:
    container_name: cluster20-17
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-17
    environment:
      CLUSTER_PEERNAME: cluster20-17
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-17/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-17:/data/ipfs-cluster

##################################################################################
## Cluster PEER 18 ################################################################
##################################################################################
  ipfs20-18:
    container_name: ipfs20-18
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-18:/data/ipfs

  cluster20-18:
    container_name: cluster20-18
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-18
    environment:
      CLUSTER_PEERNAME: cluster20-18
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-18/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-18:/data/ipfs-cluster


##################################################################################
## Cluster PEER 19 ################################################################
##################################################################################
  ipfs20-19:
    container_name: ipfs20-19
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs20-19:/data/ipfs

  cluster20-19:
    container_name: cluster20-19
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs20-19
    environment:
      CLUSTER_PEERNAME: cluster20-19
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs20-19/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster20-19:/data/ipfs-cluster
  
# For adding more peers, copy PEER 1 and rename things to ipfs20-2, cluster20-2.
# Keep bootstrapping to cluster20-10-0.